### ISSUE TITLE
Inside buttons

### ISSUE THREAD

**Issue by srq5** [stevensammon/friday-night#25]
The buttons for "diet" and "lazy" are still not quite working right.

**Comment by ewartle** [comment]
We noticed this yesterday when we were merging into master and I think it is resolved in the current master version.  Steven, when we merge your work into master this morning, let's be mindful of this.

Thanks!

**Comment by ewartle** [comment]
Oops -- I probably shouldn't have resolved this until after we merge Steven's work.  Sorry!
